apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver1-deployment 
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        name: webserver-1
    spec:
      containers:
      - name: webserver-1
        image: jaskeerat/kubernetes_101:webserver_1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver2-deployment 
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        name: webserver-2 
    spec:
      containers:
      - name: webserver-2
        image: jaskeerat/kubernetes_101:webserver_2 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver3-deployment 
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        name: webserver-3
    spec:
      containers:
      - name: webserver-3
        image: jaskeerat/kubernetes_101:webserver_3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
